"""v4

Revision ID: 8c4141190bc4
Revises: 3995b65e9996
Create Date: 2021-11-09 22:50:07.572933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4141190bc4'
down_revision = '3995b65e9996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('md5', sa.String(length=32), nullable=True))
    op.add_column('file', sa.Column('sha256', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'sha256')
    op.drop_column('file', 'md5')
    # ### end Alembic commands ###
